### ISSUE TITLE
CLI hangs

### ISSUE THREAD

**Issue by smani** [wavedrom/cli#2]
I followed the steps below:

 1. Install PhantomJS version 2.0 from http://phantomjs.org/download.html 
 2. Install version 4.2.4 from https://nodejs.org/en/download/ to obtain the `npm`.
 3. Run `npm i wavedrom-cli --save-dev`
 4. Run `phantomjs node_modules\.bin\wavedrom -i path\to\sample.json -p sample.png -s sample.svg`

The phantomjs command never terminates (I waited for more than 30mins).

I am using Windows 7 64 bit operating system.

**Comment by drom** [comment]
@smani could you try with PhantomJS v2.1.1 ?

**Comment by drom** [comment]
Looks like symbolic links on Windows don't work as expected. Please try:
`phantomjs node_modules\wavedrom-cli\bin\wavedrom-cli.js -i path\to\sample.json -p sample.png -s sample.svg`

**Comment by smani** [comment]
This command worked but the output PNG/SVG is no way related to the input. It seems to have some sample waveform (clk, Data and Request lines -- the Data line has \<head>\<body>\<tail> in different colors).

BTW, I tried `phantomjs node_modules\wavedrom-cli\bin\wavedrom-cli.js -p sample.png` and it produces the same output as `phantomjs node_modules\wavedrom-cli\bin\wavedrom-cli.js -i path\to\sample.json -p sample.png`. It looks as if the `sample.json` isn't used by the tool.

**Comment by drom** [comment]
@smani Your are absolutely right! My bad. Please try v0.3.0

**Comment by smani** [comment]
Wow! It works now. Thank you.

**Comment by drom** [comment]
great. closing.
