### ISSUE TITLE
cli version doesn't render signal groupings

### ISSUE THREAD

**Issue by itsayellow** [wavedrom/cli#3]
The signal groupings is made in javascript by grouping signals into an array, and shows up in GUI wavedrom with a bracket and sideways text on the left side.

In the CLI version I don't see any of the text and brackets on the left side for code that renders properly in the GUI wavedrom.

**Comment by drom** [comment]
yes, I confirm issue. Working on it.

**Comment by drom** [comment]
@itsayellow could you try new version v0.3.1 ?

**Comment by itsayellow** [comment]
Yes, works for me now.  Thanks!
