### ISSUE TITLE
working offline

### ISSUE THREAD

**Issue by vermaete** [wavedrom/cli#7]
As far as I understood, it is not possible to run 'phantomjs wavedrom-cli.js' without have internet access.
Is there a way to have it working or installed without the need of an connection when building the wavefrom?

**Comment by drom** [comment]
@vermaete yes, you are correct, skin files loaded fro the CDN. It make sense to package them with CLI tool. I will try to fix it soon.

**Comment by drom** [comment]
@vermaete please try v0.5.0

**Comment by vermaete** [comment]
It's working.  Tnx
